### ISSUE TITLE
Tarea 1.3

### ISSUE THREAD

**Issue by audelrpg** [SistemasTecTlaxiaco/cursogithubaudel#3]
![image](https://user-images.githubusercontent.com/89793310/131379297-aa3adc12-8e1e-4ae6-8f09-26af62751c2f.png)

![image](https://user-images.githubusercontent.com/89793310/131379145-b5b9e48d-b48b-4548-b23e-80147086ac8f.png)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
